### ISSUE TITLE
Missing Module

### ISSUE THREAD

**Issue by Arnau97** [Cardinal-Project/Cardinal#3]
Hi, it says Missing module: app.js (Ignore the other issue, i just copied the app.js from another bot)

![image](https://user-images.githubusercontent.com/68655033/97112074-9a2d1d80-16e2-11eb-9cd3-155d7832d4f2.png)

**Comment by Ciborn** [comment]
Hello,
Firstly, it looks like you want to make the bot working by copying working files from an another bot, but you do not not seem to to understand that the file you are trying to use as a replacement has nothing to do with the one you're supposed to use.
Secondly, before trying to do anything with a repository, you are supposed to read the README and the LICENCE files, if any. The instructions to help you run the bot are there.

**Comment by Arnau97** [comment]
Ciborn, the repository have no app.js, so i tryed to use another app.js from another bot.

**Comment by Arnau97** [comment]
so, what i do?
